[package]
name = "dmesg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmesg = "1.0.16"
serial = "0.4.0"
ascii = '1.0.0'